# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
