# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0004_comment_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
