# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0002_auto_20161114_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='specialty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
