# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0003_auto_20161207_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='date updated'),
        ),
    ]
