# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0005_auto_20161208_0846'),
        ('ProjectsApp', '0005_auto_20161208_0914'),
    ]

    operations = [
    ]
