# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='about',
            field=models.TextField(default='Nothing here :('),
        ),
    ]
