# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0005_auto_20161208_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='qualifications',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='specification',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
