# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 04:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UniversitiesApp', '0005_auto_20161114_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(related_name='course_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
