# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0006_auto_20161206_0432'),
        ('UniversitiesApp', '0006_auto_20161206_0457'),
    ]

    operations = [
    ]
