# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0007_merge_20161206_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(related_name='course_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
